#!/bin/bash

# 🚀 Valentine Gallery - Guía Rápida de Inicio
# Una aplicación fullstack elegante para compartir momentos especiales

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        💌 ¡Bienvenido a Valentine Gallery! 💌                 ║"
echo "║                                                                ║"
echo "║  Galería elegante de San Valentín con fotos, música y video   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 CONTENIDO DEL PROYECTO:"
echo "   ✅ Frontend Next.js 14 con React 18"
echo "   ✅ Backend Express.js + Node.js"
echo "   ✅ Galería de fotos responsiva"
echo "   ✅ Reproductor de música integrado"
echo "   ✅ Reproductor de video principal"
echo "   ✅ Panel para subir contenido"
echo "   ✅ Tema elegante de San Valentín"
echo "   ✅ Ilustraciones sutiles y animaciones"
echo ""

echo "🎨 CARACTERÍSTICAS DE DISEÑO:"
echo "   • Colores: Rosa (#ec4899), Vino (#db2777), Rosado (#fbcfe8)"
echo "   • Animaciones: Flotantes, latidos, transiciones suave"
echo "   • Responsivo: Móvil, tablet, desktop"
echo "   • Navegación: Sticky con links activos"
echo ""

echo "🚀 PARA EMPEZAR:"
echo ""
echo "   1. Abre una terminal en la carpeta del proyecto"
echo "   2. Ejecuta: npm run dev"
echo "   3. Abre en tu navegador:"
echo "      • Frontend: http://localhost:3000"
echo "      • API: http://localhost:3001/api/health"
echo ""

echo "📸 PRIMEROS PASOS:"
echo ""
echo "   1. Ve a http://localhost:3000"
echo "   2. Haz clic en 'Subir' en la navegación"
echo "   3. Completa el formulario con URLs reales:"
echo ""
echo "      Foto de ejemplo:"
echo "      https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=400&q=80"
echo ""
echo "      Canción de ejemplo:"
echo "      https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"
echo ""
echo "      Video de ejemplo:"
echo "      https://commondatastorage.googleapis.com/gtv-videos-library/sample/BigBuckBunny.mp4"
echo ""

echo "📁 ESTRUCTURA IMPORTANTE:"
echo ""
echo "   miangy/"
echo "   ├── frontend/"
echo "   │   ├── pages/"
echo "   │   │   ├── index.js       ← Galería principal"
echo "   │   │   └── upload.js      ← Panel de subida"
echo "   │   └── styles/            ← Estilos (tema San Valentín)"
echo "   ├── api/"
echo "   │   └── server.js          ← Endpoints del API"
echo "   └── *.md                   ← Documentación"
echo ""

echo "📚 DOCUMENTACIÓN:"
echo "   • README.md        - Documentación completa"
echo "   • WELCOME.md       - Guía detallada"
echo "   • SETUP.md         - Configuración"
echo "   • DEPLOY.md        - Despliegue en Vercel"
echo ""

echo "🌐 DESPLEGAR EN VERCEL:"
echo ""
echo "   1. Crea un repositorio en GitHub"
echo "   2. Sube tu código:"
echo "      git remote add origin https://github.com/TU_USUARIO/miangy.git"
echo "      git push -u origin main"
echo ""
echo "   3. Ve a vercel.com y conecta GitHub"
echo "   4. Selecciona 'miangy' y hace deploy"
echo "   5. ¡Listo! Tu app estará en vivo"
echo ""

echo "💡 TIPS IMPORTANTES:"
echo "   • Las URLs deben ser directas a los archivos (HTTPS)"
echo "   • Las fotos se ven mejor comprimidas"
echo "   • MP3 para música, MP4 para video"
echo "   • Personaliza los colores editando globals.css"
echo ""

echo "🆘 SI TIENES PROBLEMAS:"
echo ""
echo "   Error: \"Cannot GET /upload\""
echo "   → Ejecuta: npm run dev"
echo ""
echo "   Error: CORS errors"
echo "   → Verifica NEXT_PUBLIC_API_URL en .env.local"
echo ""
echo "   Error: Fotos no cargan"
echo "   → Usa URLs directas a imágenes, no páginas HTML"
echo ""
echo "   Error: API no responde"
echo "   → Verifica que ambos servidores estén corriendo"
echo ""

echo "✨ ¡APLICACIÓN LISTA PARA USAR!"
echo ""
echo "   Próximos pasos:"
echo "   1. Ejecuta: npm run dev"
echo "   2. Abre: http://localhost:3000"
echo "   3. Sube tus contenidos"
echo "   4. ¡Comparte tus momentos especiales!"
echo ""
echo "   Made with ❤️ for Special Moments"
echo ""
